kind: pipeline
name: main

steps:

- name: deploy
  image: drillster/drone-rsync
  settings:
    key:
      from_secret: m
    target: /root/pub/Configuration
    hosts:
      - iife.xyz
    user: root
    port: 22
    source: .
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master