[env]
NVIM_LEVEL = "x"
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "MonaspiceAr Nerd Font Mono"

[font.offset]
x = 0
y = 1

[terminal.shell]
program = "nu"

[window]
decorations = "none"

[terminal]
