[env]
NVIM_LEVEL = "x"
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "Monaspace Argon"

[font.offset]
x = 0
y = 3

[shell]
program = "/usr/local/bin/nu"

[window]
decorations = "none"
startup_mode = "Maximized"
