[env]
NVIM_LEVEL = "x"
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "MonaspiceAr Nerd Font Mono"

[font.offset]
x = 0
y = 3

[terminal.shell]
program = "nu"

[window]
decorations = "transparent"
#startup_mode = "Maximized"

[terminal]
