[env]
NVIM_LEVEL = "x"
NVIM_LIGHT = "0"
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
x = 0
y = 1

[window]
decorations = "none"
startup_mode = "Maximized"

[terminal.shell]
program = "nu"
args = ["-c", "zellij attach -c local" ]
