[font]
normal = ["MonaspiceAr NFM"]
size = 21


[font.features]
"MonaspiceAr NFM" = [ "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08", "+calt", "+dlig" ]

[box-drawing]
mode = "native"
