startup = [
    # "ls $'($nu.config-path | path dirname)/*.nu' | where ($it.name | path parse | get stem) != 'init' | get name | each { source $it }",
    "ls $'($nu.config-path | path dirname)/*.nu' | where ($it.name | path parse | get stem) != 'init' | get name | each { echo $\"source ($it)\n\" } | save __init.nu",
    "source ./__init.nu"
]
table_mode = "light" # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
