sync:
    #!/usr/bin/env bash
    cat configuration.nix | ssh nix 'sudo tee /etc/nixos/configuration.nix'
    ssh nix 'sudo nixos-rebuild switch'

upload:
    #!/usr/bin/env bash
    for f in configuration.nix partitions.sh; do
        echo upload $f
        curl -# -L -T ${f} file.s/${f}
    done
