FROM nnurphy/apk

ENV UID=1000
ENV USER={{user}}
ENV HOME=/home/${USER}

RUN set -ex \
    ; useradd -ms /bin/zsh -G wheel -u ${UID} ${USER}
RUN mkdir /{{workdir}} && chown -R ${USER}:${USER} /{{workdir}}
WORKDIR /{{workdir}}
USER ${USER}