watch:
	systemctl enable wg-gen-web.service wg-gen-web.path --now

setup:
	systemctl enable wg-quick@wg0
	systemctl start wg-quick@wg0

relay:
	# on relay server
	echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
	echo "net.ipv4.conf.all.proxy_arp = 1" >> /etc/sysctl.conf
	sysctl -p /etc/sysctl.conf

config:
	docker run -d -v $PWD/data:/data -p 18080:8080 -e "WG_CONF_DIR=/data" vx3r/wg-gen-web:latest

