apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: tunnel
data:
  wg0.conf: |
    [Interface]
    Address = 10.6.6.17/32
    PrivateKey = xxx
    DNS = 10.6.6.1

    [Peer]
    PublicKey = yyy
    PresharedKey = zzz
    AllowedIPs = 10.6.0.0/16
    Endpoint = addr:port
    PersistentKeepalive = 16
